/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.55
 * Generated at: 2026-06-13 02:13:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class add_002dstudent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <title>Add Student</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("          rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("          href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        body{\r\n");
      out.write("            background:#f4f7fc;\r\n");
      out.write("            min-height:100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-card{\r\n");
      out.write("            max-width:800px;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("            margin-top:60px;\r\n");
      out.write("            border:none;\r\n");
      out.write("            border-radius:20px;\r\n");
      out.write("            box-shadow:0 8px 30px rgba(0,0,0,0.12);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-header{\r\n");
      out.write("            background:#1e4fa8;\r\n");
      out.write("            color:white;\r\n");
      out.write("            border-radius:20px 20px 0 0 !important;\r\n");
      out.write("            padding:20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-label{\r\n");
      out.write("            font-weight:600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-save{\r\n");
      out.write("            background:#1e4fa8;\r\n");
      out.write("            color:white;\r\n");
      out.write("            border:none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-save:hover{\r\n");
      out.write("            background:#163b7a;\r\n");
      out.write("            color:white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card form-card\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("\r\n");
      out.write("            <h3 class=\"mb-0\">\r\n");
      out.write("                <i class=\"fa-solid fa-user-plus\"></i>\r\n");
      out.write("                Add New Student\r\n");
      out.write("            </h3>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-body p-4\">\r\n");
      out.write("\r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath());
      out.write("/add-student\"\r\n");
      out.write("                  method=\"post\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-6 mb-3\">\r\n");
      out.write("\r\n");
      out.write("                        <label class=\"form-label\">\r\n");
      out.write("                            Full Name\r\n");
      out.write("                        </label>\r\n");
      out.write("\r\n");
      out.write("                        <input type=\"text\"\r\n");
      out.write("                               name=\"name\"\r\n");
      out.write("                               class=\"form-control\"\r\n");
      out.write("                               required>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-6 mb-3\">\r\n");
      out.write("\r\n");
      out.write("                        <label class=\"form-label\">\r\n");
      out.write("                            USN\r\n");
      out.write("                        </label>\r\n");
      out.write("\r\n");
      out.write("                        <input type=\"text\"\r\n");
      out.write("                               name=\"usn\"\r\n");
      out.write("                               class=\"form-control\"\r\n");
      out.write("                               required>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-6 mb-3\">\r\n");
      out.write("\r\n");
      out.write("                        <label class=\"form-label\">\r\n");
      out.write("                            Branch\r\n");
      out.write("                        </label>\r\n");
      out.write("\r\n");
      out.write("                        <input type=\"text\"\r\n");
      out.write("                               name=\"branch\"\r\n");
      out.write("                               class=\"form-control\"\r\n");
      out.write("                               placeholder=\"Computer Science - Data Science\"\r\n");
      out.write("                               required>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-6 mb-3\">\r\n");
      out.write("\r\n");
      out.write("                        <label class=\"form-label\">\r\n");
      out.write("                            Semester\r\n");
      out.write("                        </label>\r\n");
      out.write("\r\n");
      out.write("                        <select name=\"semester\"\r\n");
      out.write("                                class=\"form-select\">\r\n");
      out.write("\r\n");
      out.write("                            <option value=\"1\">Semester 1</option>\r\n");
      out.write("                            <option value=\"2\">Semester 2</option>\r\n");
      out.write("                            <option value=\"3\">Semester 3</option>\r\n");
      out.write("                            <option value=\"4\">Semester 4</option>\r\n");
      out.write("                            <option value=\"5\">Semester 5</option>\r\n");
      out.write("                            <option value=\"6\">Semester 6</option>\r\n");
      out.write("                            <option value=\"7\">Semester 7</option>\r\n");
      out.write("                            <option value=\"8\">Semester 8</option>\r\n");
      out.write("\r\n");
      out.write("                        </select>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-12 mb-4\">\r\n");
      out.write("\r\n");
      out.write("                        <label class=\"form-label\">\r\n");
      out.write("                            Department\r\n");
      out.write("                        </label>\r\n");
      out.write("\r\n");
      out.write("                        <input type=\"text\"\r\n");
      out.write("                               name=\"department\"\r\n");
      out.write("                               class=\"form-control\"\r\n");
      out.write("                               placeholder=\"CSE-DS\"\r\n");
      out.write("                               required>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"d-flex justify-content-between\">\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/students\"\r\n");
      out.write("                       class=\"btn btn-secondary\">\r\n");
      out.write("\r\n");
      out.write("                        <i class=\"fa-solid fa-arrow-left\"></i>\r\n");
      out.write("                        Back\r\n");
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\"\r\n");
      out.write("                            class=\"btn btn-save px-4\">\r\n");
      out.write("\r\n");
      out.write("                        <i class=\"fa-solid fa-floppy-disk\"></i>\r\n");
      out.write("                        Save Student\r\n");
      out.write("\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
