/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.55
 * Generated at: 2026-06-12 21:24:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class admin_002ddashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Admin Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("*{\r\n");
      out.write("    margin:0;\r\n");
      out.write("    padding:0;\r\n");
      out.write("    box-sizing:border-box;\r\n");
      out.write("    font-family:'Poppins',sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("    background:#f4f7fc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* SIDEBAR */\r\n");
      out.write("\r\n");
      out.write(".sidebar{\r\n");
      out.write("    width:250px;\r\n");
      out.write("    height:100vh;\r\n");
      out.write("    position:fixed;\r\n");
      out.write("    background:#1f4ea8;\r\n");
      out.write("    color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo{\r\n");
      out.write("    padding:25px;\r\n");
      out.write("    font-size:22px;\r\n");
      out.write("    font-weight:700;\r\n");
      out.write("    border-bottom:1px solid rgba(255,255,255,.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu{\r\n");
      out.write("    margin-top:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu a{\r\n");
      out.write("    display:block;\r\n");
      out.write("    color:white;\r\n");
      out.write("    text-decoration:none;\r\n");
      out.write("    padding:15px 25px;\r\n");
      out.write("    transition:.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu a:hover{\r\n");
      out.write("    background:rgba(255,255,255,.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* MAIN */\r\n");
      out.write("\r\n");
      out.write(".main{\r\n");
      out.write("    margin-left:250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* TOPBAR */\r\n");
      out.write("\r\n");
      out.write(".topbar{\r\n");
      out.write("    background:white;\r\n");
      out.write("    height:70px;\r\n");
      out.write("    display:flex;\r\n");
      out.write("    justify-content:space-between;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    padding:0 40px;\r\n");
      out.write("    box-shadow:0 2px 10px rgba(0,0,0,.08);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topbar h2{\r\n");
      out.write("    color:#333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile{\r\n");
      out.write("    font-weight:600;\r\n");
      out.write("    color:#1f4ea8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* CONTENT */\r\n");
      out.write("\r\n");
      out.write(".content{\r\n");
      out.write("    padding:40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cards{\r\n");
      out.write("    display:grid;\r\n");
      out.write("    grid-template-columns:repeat(4,1fr);\r\n");
      out.write("    gap:25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card{\r\n");
      out.write("    background:white;\r\n");
      out.write("    border-radius:15px;\r\n");
      out.write("    padding:25px;\r\n");
      out.write("    box-shadow:0 5px 15px rgba(0,0,0,.08);\r\n");
      out.write("    transition:.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card:hover{\r\n");
      out.write("    transform:translateY(-5px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-title{\r\n");
      out.write("    color:#777;\r\n");
      out.write("    font-size:15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-value{\r\n");
      out.write("    font-size:40px;\r\n");
      out.write("    font-weight:700;\r\n");
      out.write("    margin-top:10px;\r\n");
      out.write("    color:#1f4ea8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section{\r\n");
      out.write("    margin-top:35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".panel{\r\n");
      out.write("    background:white;\r\n");
      out.write("    border-radius:15px;\r\n");
      out.write("    padding:25px;\r\n");
      out.write("    box-shadow:0 5px 15px rgba(0,0,0,.08);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".panel h3{\r\n");
      out.write("    margin-bottom:15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".activity{\r\n");
      out.write("    padding:12px 0;\r\n");
      out.write("    border-bottom:1px solid #eee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* QUICK ACTIONS */\r\n");
      out.write("\r\n");
      out.write(".actions{\r\n");
      out.write("    display:flex;\r\n");
      out.write("    gap:15px;\r\n");
      out.write("    margin-top:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn{\r\n");
      out.write("    padding:12px 20px;\r\n");
      out.write("    background:#1f4ea8;\r\n");
      out.write("    color:white;\r\n");
      out.write("    text-decoration:none;\r\n");
      out.write("    border-radius:8px;\r\n");
      out.write("    font-size:14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:hover{\r\n");
      out.write("    background:#163d86;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- SIDEBAR -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("        ETS Portal\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"menu\">\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/dashboard\">\r\n");
      out.write("            Dashboard\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/students\">\r\n");
      out.write("            Students\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("            Subjects\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("            Attendance\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("            Eligibility\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("            Admit Cards\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath());
      out.write("/logout\">\r\n");
      out.write("            Logout\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- MAIN -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("    <!-- TOP BAR -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"topbar\">\r\n");
      out.write("\r\n");
      out.write("        <h2>Dashboard</h2>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"profile\">\r\n");
      out.write("            Welcome Admin\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- CONTENT -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"cards\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <div class=\"card-title\">\r\n");
      out.write("                    Total Students\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-value\">\r\n");
      out.write("                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studentCount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <div class=\"card-title\">\r\n");
      out.write("                    Subjects\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-value\">\r\n");
      out.write("                    12\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <div class=\"card-title\">\r\n");
      out.write("                    Faculty\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-value\">\r\n");
      out.write("                    18\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <div class=\"card-title\">\r\n");
      out.write("                    Eligible Students\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-value\">\r\n");
      out.write("                    4\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"section\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"panel\">\r\n");
      out.write("\r\n");
      out.write("                <h3>Quick Actions</h3>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"actions\">\r\n");
      out.write("\r\n");
      out.write("                    <a class=\"btn\"\r\n");
      out.write("                       href=\"");
      out.print(request.getContextPath());
      out.write("/students\">\r\n");
      out.write("                        Manage Students\r\n");
      out.write("                    </a>\r\n");
      out.write("\r\n");
      out.write("                    <a class=\"btn\"\r\n");
      out.write("                       href=\"");
      out.print(request.getContextPath());
      out.write("/jsp/import-students.jsp\">\r\n");
      out.write("                        Import CSV\r\n");
      out.write("                    </a>\r\n");
      out.write("\r\n");
      out.write("                    <a class=\"btn\"\r\n");
      out.write("                       href=\"");
      out.print(request.getContextPath());
      out.write("/jsp/export-filter.jsp\">\r\n");
      out.write("                        Export CSV\r\n");
      out.write("                    </a>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"section\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"panel\">\r\n");
      out.write("\r\n");
      out.write("                <h3>Recent Activity</h3>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"activity\">\r\n");
      out.write("                    Student records updated\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"activity\">\r\n");
      out.write("                    CSV imported successfully\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"activity\">\r\n");
      out.write("                    Dashboard loaded\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
