/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.55
 * Generated at: 2026-06-12 21:40:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class import_002dstudents_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <title>Import Students CSV</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("          rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("          href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        body{\r\n");
      out.write("            background:#f4f7fc;\r\n");
      out.write("            min-height:100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .upload-card{\r\n");
      out.write("            max-width:850px;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("            margin-top:60px;\r\n");
      out.write("            border:none;\r\n");
      out.write("            border-radius:20px;\r\n");
      out.write("            overflow:hidden;\r\n");
      out.write("            box-shadow:0 8px 25px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-header{\r\n");
      out.write("            background:#198754;\r\n");
      out.write("            color:white;\r\n");
      out.write("            padding:20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .upload-zone{\r\n");
      out.write("            border:2px dashed #198754;\r\n");
      out.write("            border-radius:15px;\r\n");
      out.write("            padding:50px;\r\n");
      out.write("            text-align:center;\r\n");
      out.write("            background:#f8fffa;\r\n");
      out.write("            transition:.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .upload-zone:hover{\r\n");
      out.write("            background:#eefcf3;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .upload-icon{\r\n");
      out.write("            font-size:60px;\r\n");
      out.write("            color:#198754;\r\n");
      out.write("            margin-bottom:15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-upload{\r\n");
      out.write("            background:#198754;\r\n");
      out.write("            color:white;\r\n");
      out.write("            border:none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-upload:hover{\r\n");
      out.write("            background:#146c43;\r\n");
      out.write("            color:white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-box{\r\n");
      out.write("            background:#f8f9fa;\r\n");
      out.write("            border-left:4px solid #198754;\r\n");
      out.write("            padding:15px;\r\n");
      out.write("            border-radius:10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card upload-card\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("\r\n");
      out.write("            <h3 class=\"mb-0\">\r\n");
      out.write("                <i class=\"fa-solid fa-file-csv\"></i>\r\n");
      out.write("                Import Students CSV\r\n");
      out.write("            </h3>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-body p-4\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"info-box mb-4\">\r\n");
      out.write("\r\n");
      out.write("                <strong>CSV Format Required:</strong>\r\n");
      out.write("\r\n");
      out.write("                <br><br>\r\n");
      out.write("\r\n");
      out.write("                Full Name, Department Name, USN, Temp Roll(If not available, leave blank), Semester, Department Code\r\n");
      out.write("\r\n");
      out.write("                <br>\r\n");
      out.write("\r\n");
      out.write("                Example:\r\n");
      out.write("\r\n");
      out.write("                <br>\r\n");
      out.write("\r\n");
      out.write("                Radhika D Chougale,\r\n");
      out.write("                Computer Science - Data Science,\r\n");
      out.write("                1DT24CD036,\r\n");
      out.write("                ,\r\n");
      out.write("                4,\r\n");
      out.write("                CS-DS\r\n");
      out.write("\r\n");
      out.write("                <br>\r\n");
      out.write("              \r\n");
      out.write("                <br>\r\n");
      out.write("\r\n");
      out.write("                Rahul,\r\n");
      out.write("                Computer Science - Data Science,\r\n");
      out.write("                1DT24CD037,\r\n");
      out.write("                ,\r\n");
      out.write("                4,\r\n");
      out.write("                CSE-DS\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath());
      out.write("/import-students\"\r\n");
      out.write("                  method=\"post\"\r\n");
      out.write("                  enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"upload-zone\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"upload-icon\">\r\n");
      out.write("\r\n");
      out.write("                        <i class=\"fa-solid fa-cloud-arrow-up\"></i>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <h4>Select Student CSV File</h4>\r\n");
      out.write("\r\n");
      out.write("                    <p class=\"text-muted\">\r\n");
      out.write("                        Upload student records in CSV format\r\n");
      out.write("                    </p>\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"file\"\r\n");
      out.write("                           name=\"csvFile\"\r\n");
      out.write("                           class=\"form-control mt-3\"\r\n");
      out.write("                           accept=\".csv\"\r\n");
      out.write("                           required>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"d-flex justify-content-between mt-4\">\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/students\"\r\n");
      out.write("                       class=\"btn btn-secondary\">\r\n");
      out.write("\r\n");
      out.write("                        <i class=\"fa-solid fa-arrow-left\"></i>\r\n");
      out.write("                        Back\r\n");
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\"\r\n");
      out.write("                            class=\"btn btn-upload px-4\">\r\n");
      out.write("\r\n");
      out.write("                        <i class=\"fa-solid fa-upload\"></i>\r\n");
      out.write("                        Upload CSV\r\n");
      out.write("\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
