/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.55
 * Generated at: 2026-07-05 15:19:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Examination Ticketing System</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&family=Playfair+Display:wght@600;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("*{\r\n");
      out.write("    margin:0;\r\n");
      out.write("    padding:0;\r\n");
      out.write("    box-sizing:border-box;\r\n");
      out.write("    font-family:'Poppins',sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("    height:100vh;\r\n");
      out.write("    overflow:hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container{\r\n");
      out.write("    display:flex;\r\n");
      out.write("    height:100vh;\r\n");
      out.write("    width:100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* LEFT SIDE */\r\n");
      out.write("\r\n");
      out.write(".left-panel{\r\n");
      out.write("    width:70%;\r\n");
      out.write("    position:relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".left-panel img{\r\n");
      out.write("    width:100%;\r\n");
      out.write("    height:100%;\r\n");
      out.write("    object-fit:cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".overlay{\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    inset:0;\r\n");
      out.write("    background:rgba(0,0,0,0.25);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".project-title{\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    top:60px;\r\n");
      out.write("    left:60px;\r\n");
      out.write("    color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".project-title h1{\r\n");
      out.write("    font-size:48px;\r\n");
      out.write("    font-weight:700;\r\n");
      out.write("    line-height:1.2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".project-title p{\r\n");
      out.write("    margin-top:20px;\r\n");
      out.write("    font-size:18px;\r\n");
      out.write("    opacity:0.95;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* RIGHT SIDE */\r\n");
      out.write("\r\n");
      out.write(".right-panel{\r\n");
      out.write("    width:30%;\r\n");
      out.write("    background:white;\r\n");
      out.write("    display:flex;\r\n");
      out.write("    justify-content:center;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-card{\r\n");
      out.write("    width:85%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo{\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    margin-bottom:25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo img{\r\n");
      out.write("    width:110px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo h2{\r\n");
      out.write("    color:#1f4ea8;\r\n");
      out.write("    margin-top:10px;\r\n");
      out.write("    font-size:28px;\r\n");
      out.write("    font-weight:700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo p{\r\n");
      out.write("    color:#666;\r\n");
      out.write("    font-size:14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group{\r\n");
      out.write("    margin-bottom:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group label{\r\n");
      out.write("    display:block;\r\n");
      out.write("    margin-bottom:8px;\r\n");
      out.write("    font-weight:500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control{\r\n");
      out.write("    width:100%;\r\n");
      out.write("    padding:14px;\r\n");
      out.write("    border:1px solid #d9d9d9;\r\n");
      out.write("    border-radius:8px;\r\n");
      out.write("    font-size:15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control:focus{\r\n");
      out.write("    outline:none;\r\n");
      out.write("    border-color:#1f4ea8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-btn{\r\n");
      out.write("    width:100%;\r\n");
      out.write("    padding:14px;\r\n");
      out.write("    border:none;\r\n");
      out.write("    border-radius:8px;\r\n");
      out.write("    background:#1f4ea8;\r\n");
      out.write("    color:white;\r\n");
      out.write("    font-size:16px;\r\n");
      out.write("    font-weight:600;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("    transition:.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-btn:hover{\r\n");
      out.write("    background:#163c84;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".error{\r\n");
      out.write("    color:red;\r\n");
      out.write("    margin-bottom:15px;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-text{\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    margin-top:20px;\r\n");
      out.write("    color:#888;\r\n");
      out.write("    font-size:13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media(max-width:900px){\r\n");
      out.write("\r\n");
      out.write("    .left-panel{\r\n");
      out.write("        display:none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .right-panel{\r\n");
      out.write("        width:100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <!-- LEFT IMAGE -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"left-panel\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Replace image path -->\r\n");
      out.write("        <img src=\"");
      out.print(request.getContextPath());
      out.write("/image/dsatm-campus.png\" alt=\"Campus\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"overlay\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"project-title\">\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- LOGIN PANEL -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"right-panel\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"login-card\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Replace logo path -->\r\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/image/dsatm-logo.png\"\r\n");
      out.write("                    alt=\"DSATM Logo\"\r\n");
      out.write("                        class=\"dsatm-logo\">\r\n");
      out.write("                <h2>DSATM</h2>\r\n");
      out.write("\r\n");
      out.write("                <h2>Examination Management Portal</h2>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");
 if(request.getParameter("error") != null){ 
      out.write("\r\n");
      out.write("                <div class=\"error\">\r\n");
      out.write("                    Invalid Username or Password\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath());
      out.write("/login\"\r\n");
      out.write("                  method=\"post\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label>Username</label>\r\n");
      out.write("                    <input type=\"text\"\r\n");
      out.write("                           name=\"username\"\r\n");
      out.write("                           class=\"form-control\"\r\n");
      out.write("                           required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label>Password</label>\r\n");
      out.write("                    <input type=\"password\"\r\n");
      out.write("                           name=\"password\"\r\n");
      out.write("                           class=\"form-control\"\r\n");
      out.write("                           required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button class=\"login-btn\">\r\n");
      out.write("                    Login\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"footer-text\">\r\n");
      out.write("                © 2026 DSATM Examination Department\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
