/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.55
 * Generated at: 2026-06-12 21:29:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import model.Student;

public final class students_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.Student");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

List<Student> students =
        (List<Student>) request.getAttribute("students");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <title>Student Management</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("          rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("          href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        body{\r\n");
      out.write("            background:#f4f7fc;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page-title{\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("            color:#1e3c72;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card{\r\n");
      out.write("            border:none;\r\n");
      out.write("            border-radius:15px;\r\n");
      out.write("            box-shadow:0 4px 15px rgba(0,0,0,0.08);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .stats-card h2{\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table{\r\n");
      out.write("            margin-bottom:0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table thead{\r\n");
      out.write("            background:#1e4fa8;\r\n");
      out.write("            color:white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table th{\r\n");
      out.write("            padding:15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table td{\r\n");
      out.write("            vertical-align:middle;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn{\r\n");
      out.write("            border-radius:10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-box{\r\n");
      out.write("            border-radius:10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid p-4\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HEADER -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("\r\n");
      out.write("            <h2 class=\"page-title\">\r\n");
      out.write("                Student Management\r\n");
      out.write("            </h2>\r\n");
      out.write("\r\n");
      out.write("            <p class=\"text-muted mb-0\">\r\n");
      out.write("                Manage students, imports, exports and records\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"jsp/add-student.jsp\"\r\n");
      out.write("           class=\"btn btn-primary\">\r\n");
      out.write("\r\n");
      out.write("            <i class=\"fa-solid fa-user-plus\"></i>\r\n");
      out.write("            Add Student\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- STATISTICS -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row mb-4\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card stats-card\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("                    <h6 class=\"text-muted\">\r\n");
      out.write("                        Total Students\r\n");
      out.write("                    </h6>\r\n");
      out.write("\r\n");
      out.write("                    <h2 class=\"text-primary\">\r\n");
      out.write("                        ");
      out.print( students == null ? 0 : students.size() );
      out.write("\r\n");
      out.write("                    </h2>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card stats-card\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("                    <h6 class=\"text-muted\">\r\n");
      out.write("                        Department\r\n");
      out.write("                    </h6>\r\n");
      out.write("\r\n");
      out.write("                    <h2 class=\"text-success\">\r\n");
      out.write("                        CSE-DS\r\n");
      out.write("                    </h2>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card stats-card\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("                    <h6 class=\"text-muted\">\r\n");
      out.write("                        Semester\r\n");
      out.write("                    </h6>\r\n");
      out.write("\r\n");
      out.write("                    <h2 class=\"text-warning\">\r\n");
      out.write("                        3\r\n");
      out.write("                    </h2>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card stats-card\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("                    <h6 class=\"text-muted\">\r\n");
      out.write("                        Active Records\r\n");
      out.write("                    </h6>\r\n");
      out.write("\r\n");
      out.write("                    <h2 class=\"text-danger\">\r\n");
      out.write("                        ");
      out.print( students == null ? 0 : students.size() );
      out.write("\r\n");
      out.write("                    </h2>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ACTION BAR -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card mb-4\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row g-2\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"jsp/import-students.jsp\"\r\n");
      out.write("                       class=\"btn btn-success w-100\">\r\n");
      out.write("\r\n");
      out.write("                        <i class=\"fa-solid fa-file-import\"></i>\r\n");
      out.write("                        Import CSV\r\n");
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"jsp/export-filter.jsp\"\r\n");
      out.write("                       class=\"btn btn-warning text-white w-100\">\r\n");
      out.write("\r\n");
      out.write("                        <i class=\"fa-solid fa-file-export\"></i>\r\n");
      out.write("                        Export By Branch & Semester\r\n");
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("\r\n");
      out.write("                    <form action=\"search-student\" method=\"get\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"text\"\r\n");
      out.write("                                   name=\"keyword\"\r\n");
      out.write("                                   class=\"form-control search-box\"\r\n");
      out.write("                                   placeholder=\"Search by Name / USN / Temp Roll\">\r\n");
      out.write("\r\n");
      out.write("                            <button class=\"btn btn-primary\">\r\n");
      out.write("\r\n");
      out.write("                                <i class=\"fa-solid fa-magnifying-glass\"></i>\r\n");
      out.write("\r\n");
      out.write("                            </button>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- TABLE -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-header bg-primary text-white\">\r\n");
      out.write("\r\n");
      out.write("            <h5 class=\"mb-0\">\r\n");
      out.write("\r\n");
      out.write("                <i class=\"fa-solid fa-users\"></i>\r\n");
      out.write("                Student Records\r\n");
      out.write("\r\n");
      out.write("            </h5>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-body p-0\">\r\n");
      out.write("\r\n");
      out.write("            <table class=\"table table-hover table-striped\">\r\n");
      out.write("\r\n");
      out.write("                <thead>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("\r\n");
      out.write("                    <th>ID</th>\r\n");
      out.write("                    <th>Name</th>\r\n");
      out.write("                    <th>USN</th>\r\n");
      out.write("                    <th>Branch</th>\r\n");
      out.write("                    <th>Semester</th>\r\n");
      out.write("                    <th>Department</th>\r\n");
      out.write("                    <th width=\"150\">Actions</th>\r\n");
      out.write("\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                </thead>\r\n");
      out.write("\r\n");
      out.write("                <tbody>\r\n");
      out.write("\r\n");
      out.write("                ");

                if(students != null){

                    for(Student s : students){
                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("\r\n");
      out.write("                    <td>");
      out.print( s.getId() );
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <strong>\r\n");
      out.write("                            ");
      out.print( s.getFullName() );
      out.write("\r\n");
      out.write("                        </strong>\r\n");
      out.write("                    </td>\r\n");
      out.write("\r\n");
      out.write("                    <td>");
      out.print( s.getUsn() );
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("                    <td>");
      out.print( s.getBranch() );
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <span class=\"badge bg-info\">\r\n");
      out.write("                            Sem ");
      out.print( s.getSemester() );
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </td>\r\n");
      out.write("\r\n");
      out.write("                    <td>");
      out.print( s.getDepartment() );
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("                    <td>\r\n");
      out.write("\r\n");
      out.write("                        <a href=\"edit-student?id=");
      out.print(s.getId());
      out.write("\"\r\n");
      out.write("                           class=\"btn btn-warning btn-sm\">\r\n");
      out.write("\r\n");
      out.write("                            <i class=\"fa-solid fa-pen\"></i>\r\n");
      out.write("\r\n");
      out.write("                        </a>\r\n");
      out.write("\r\n");
      out.write("                        <a href=\"delete-student?id=");
      out.print(s.getId());
      out.write("\"\r\n");
      out.write("                           class=\"btn btn-danger btn-sm\">\r\n");
      out.write("\r\n");
      out.write("                            <i class=\"fa-solid fa-trash\"></i>\r\n");
      out.write("\r\n");
      out.write("                        </a>\r\n");
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                ");

                    }
                }
                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
