/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.55
 * Generated at: 2026-07-11 13:43:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import model.Student;

public final class students_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.Student");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

List<Student> students =
        (List<Student>) request.getAttribute("students");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <title>Student Management</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("          rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("          href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        body{\r\n");
      out.write("            background:#f4f7fc;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page-title{\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("            color:#1e3c72;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card{\r\n");
      out.write("            border:none;\r\n");
      out.write("            border-radius:15px;\r\n");
      out.write("            box-shadow:0 4px 15px rgba(0,0,0,0.08);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .stats-card h2{\r\n");
      out.write("            font-weight:700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table{\r\n");
      out.write("            margin-bottom:0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table thead{\r\n");
      out.write("            background:#1e4fa8;\r\n");
      out.write("            color:white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table th{\r\n");
      out.write("            padding:15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table td{\r\n");
      out.write("            vertical-align:middle;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn{\r\n");
      out.write("            border-radius:10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-box{\r\n");
      out.write("            border-radius:10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Semester tabs */\r\n");
      out.write("        .sem-tab {\r\n");
      out.write("            border: 2px solid #1e4fa8;\r\n");
      out.write("            color: #1e4fa8;\r\n");
      out.write("            background: white;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            padding: 8px 18px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sem-tab:hover {\r\n");
      out.write("            background: #eaf0fd;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sem-tab.active {\r\n");
      out.write("            background: #1e4fa8;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Branch cards */\r\n");
      out.write("        .branch-card {\r\n");
      out.write("            border: 2px solid #e2e8f0;\r\n");
      out.write("            border-radius: 14px;\r\n");
      out.write("            padding: 14px 16px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            transition: all .15s ease;\r\n");
      out.write("            background: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .branch-card:hover {\r\n");
      out.write("            border-color: #1e4fa8;\r\n");
      out.write("            box-shadow: 0 4px 12px rgba(30,79,168,.15);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .branch-card.active {\r\n");
      out.write("            border-color: #1e4fa8;\r\n");
      out.write("            background: #eaf0fd;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .branch-card .branch-code {\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #1e3c72;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .branch-card .branch-count {\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            color: #6b7280;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid p-4\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HEADER -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("\r\n");
      out.write("            <h2 class=\"page-title\">\r\n");
      out.write("                Student Management\r\n");
      out.write("            </h2>\r\n");
      out.write("\r\n");
      out.write("            <p class=\"text-muted mb-0\">\r\n");
      out.write("                Manage students, imports, exports and records\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"jsp/add-student.jsp\"\r\n");
      out.write("           class=\"btn btn-primary\">\r\n");
      out.write("\r\n");
      out.write("            <i class=\"fa-solid fa-user-plus\"></i>\r\n");
      out.write("            Add Student\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- STATISTICS -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row mb-4\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card stats-card\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("                    <h6 class=\"text-muted\">\r\n");
      out.write("                        Total Students\r\n");
      out.write("                    </h6>\r\n");
      out.write("\r\n");
      out.write("                    <h2 class=\"text-primary\">\r\n");
      out.write("                        ");
      out.print( students == null ? 0 : students.size() );
      out.write("\r\n");
      out.write("                    </h2>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card stats-card\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("                    <h6 class=\"text-muted\">\r\n");
      out.write("                        Currently Viewing\r\n");
      out.write("                    </h6>\r\n");
      out.write("\r\n");
      out.write("                    <h2 class=\"text-success\" id=\"statBranchLabel\" style=\"font-size:1.4rem;\">\r\n");
      out.write("                        All Branches\r\n");
      out.write("                    </h2>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card stats-card\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("                    <h6 class=\"text-muted\">\r\n");
      out.write("                        Semester\r\n");
      out.write("                    </h6>\r\n");
      out.write("\r\n");
      out.write("                    <h2 class=\"text-warning\" id=\"statSemLabel\">\r\n");
      out.write("                        All\r\n");
      out.write("                    </h2>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card stats-card\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("                    <h6 class=\"text-muted\">\r\n");
      out.write("                        Showing\r\n");
      out.write("                    </h6>\r\n");
      out.write("\r\n");
      out.write("                    <h2 class=\"text-danger\" id=\"statCountLabel\">\r\n");
      out.write("                        ");
      out.print( students == null ? 0 : students.size() );
      out.write("\r\n");
      out.write("                    </h2>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ACTION BAR -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card mb-4\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row g-2\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"jsp/import-students.jsp\"\r\n");
      out.write("                       class=\"btn btn-success w-100\">\r\n");
      out.write("\r\n");
      out.write("                        <i class=\"fa-solid fa-file-import\"></i>\r\n");
      out.write("                        Import CSV\r\n");
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"jsp/export-filter.jsp\"\r\n");
      out.write("                       class=\"btn btn-warning text-white w-100\">\r\n");
      out.write("\r\n");
      out.write("                        <i class=\"fa-solid fa-file-export\"></i>\r\n");
      out.write("                        Export By Branch & Semester\r\n");
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("\r\n");
      out.write("                    <form action=\"search-student\" method=\"get\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"text\"\r\n");
      out.write("                                   name=\"keyword\"\r\n");
      out.write("                                   class=\"form-control search-box\"\r\n");
      out.write("                                   placeholder=\"Search by Name / USN / Temp Roll\">\r\n");
      out.write("\r\n");
      out.write("                            <button class=\"btn btn-primary\">\r\n");
      out.write("\r\n");
      out.write("                                <i class=\"fa-solid fa-magnifying-glass\"></i>\r\n");
      out.write("\r\n");
      out.write("                            </button>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- SEMESTER TABS -->\r\n");
      out.write("    <div class=\"card mb-4\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <h6 class=\"mb-3\">Select Semester</h6>\r\n");
      out.write("            <div class=\"d-flex flex-wrap gap-2\" id=\"semTabs\">\r\n");
      out.write("                <button type=\"button\" class=\"sem-tab\" onclick=\"selectSemester(1)\">Sem 1</button>\r\n");
      out.write("                <button type=\"button\" class=\"sem-tab\" onclick=\"selectSemester(2)\">Sem 2</button>\r\n");
      out.write("                <button type=\"button\" class=\"sem-tab\" onclick=\"selectSemester(3)\">Sem 3</button>\r\n");
      out.write("                <button type=\"button\" class=\"sem-tab\" onclick=\"selectSemester(4)\">Sem 4</button>\r\n");
      out.write("                <button type=\"button\" class=\"sem-tab\" onclick=\"selectSemester(5)\">Sem 5</button>\r\n");
      out.write("                <button type=\"button\" class=\"sem-tab\" onclick=\"selectSemester(6)\">Sem 6</button>\r\n");
      out.write("                <button type=\"button\" class=\"sem-tab\" onclick=\"selectSemester(7)\">Sem 7</button>\r\n");
      out.write("                <button type=\"button\" class=\"sem-tab\" onclick=\"selectSemester(8)\">Sem 8</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-outline-secondary\" onclick=\"resetFilters()\">\r\n");
      out.write("                    <i class=\"fa-solid fa-rotate-left\"></i> Show All\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- BRANCH GRID (shown after a semester is picked) -->\r\n");
      out.write("    <div class=\"card mb-4 d-none\" id=\"branchCard\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <h6 class=\"mb-3\">Select Branch &mdash; <span id=\"selectedSemLabel\"></span></h6>\r\n");
      out.write("            <div class=\"row g-3\" id=\"branchGrid\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- TABLE -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-header bg-primary text-white d-flex justify-content-between align-items-center\">\r\n");
      out.write("\r\n");
      out.write("            <h5 class=\"mb-0\">\r\n");
      out.write("\r\n");
      out.write("                <i class=\"fa-solid fa-users\"></i>\r\n");
      out.write("                Student Records\r\n");
      out.write("\r\n");
      out.write("            </h5>\r\n");
      out.write("\r\n");
      out.write("            <span id=\"tableFilterLabel\" class=\"small\"></span>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-body p-0\">\r\n");
      out.write("\r\n");
      out.write("            <table class=\"table table-hover table-striped\">\r\n");
      out.write("\r\n");
      out.write("                <thead>\r\n");
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("\r\n");
      out.write("                    <th>ID</th>\r\n");
      out.write("                    <th>Name</th>\r\n");
      out.write("                    <th>USN</th>\r\n");
      out.write("                    <th>Branch</th>\r\n");
      out.write("                    <th>Semester</th>\r\n");
      out.write("                    <th>Department</th>\r\n");
      out.write("                    <th width=\"150\">Actions</th>\r\n");
      out.write("\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                </thead>\r\n");
      out.write("\r\n");
      out.write("                <tbody id=\"studentTableBody\">\r\n");
      out.write("                </tbody>\r\n");
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"noResults\" class=\"text-center text-muted p-4 d-none\">\r\n");
      out.write("                No students found for this selection.\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    const CONTEXT_PATH = \"");
      out.print(request.getContextPath());
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("    // All students rendered server-side into a JS array for client-side filtering\r\n");
      out.write("    const allStudents = [\r\n");
      out.write("        ");

        if (students != null) {
            for (int i = 0; i < students.size(); i++) {
                Student s = students.get(i);
                String safeName = s.getFullName() == null ? "" : s.getFullName().replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "\\r");
                String usn = s.getUsn() == null ? "" : s.getUsn().replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "\\r");
                String branch = s.getBranch() == null ? "" : s.getBranch().replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "\\r");
                String dept = s.getDepartment() == null ? "" : s.getDepartment().replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "\\r");
        
      out.write("\r\n");
      out.write("        {\r\n");
      out.write("            id: ");
      out.print(s.getId());
      out.write(",\r\n");
      out.write("            name: \"");
      out.print(safeName);
      out.write("\",\r\n");
      out.write("            usn: \"");
      out.print(usn);
      out.write("\",\r\n");
      out.write("            branch: \"");
      out.print(branch);
      out.write("\",\r\n");
      out.write("            semester: ");
      out.print(s.getSemester());
      out.write(",\r\n");
      out.write("            department: \"");
      out.print(dept);
      out.write("\"\r\n");
      out.write("        }");
      out.print( (i < students.size() - 1) ? "," : "" );
      out.write("\r\n");
      out.write("        ");

            }
        }
        
      out.write("\r\n");
      out.write("    ];\r\n");
      out.write("\r\n");
      out.write("    const branches = [\r\n");
      out.write("        { code: \"AI\",       name: \"Artificial Intelligence and Machine Learning\" },\r\n");
      out.write("        { code: \"ARCH\",     name: \"Bachelor of Architecture\" },\r\n");
      out.write("        { code: \"CV\",       name: \"Civil Engineering\" },\r\n");
      out.write("        { code: \"CSE\",      name: \"Computer Science and Engineering\" },\r\n");
      out.write("        { code: \"CSD\",      name: \"Computer Science and Design\" },\r\n");
      out.write("        { code: \"CSE-AI\",   name: \"CSE (Artificial Intelligence)\" },\r\n");
      out.write("        { code: \"CSE-CY\",   name: \"CSE (Cyber Security)\" },\r\n");
      out.write("        { code: \"CSE-DS\",   name: \"CSE & Engineering (Data Science)\" },\r\n");
      out.write("        { code: \"CSE-IOT\",  name: \"CSE (IoT & Cyber Security incl. Blockchain)\" },\r\n");
      out.write("        { code: \"EEE\",      name: \"Electrical & Electronics Engineering\" },\r\n");
      out.write("        { code: \"ECE\",      name: \"Electronics and Communication Engineering\" },\r\n");
      out.write("        { code: \"ISE\",      name: \"Information Science and Engineering\" },\r\n");
      out.write("        { code: \"ME\",       name: \"Mechanical Engineering\" }\r\n");
      out.write("    ];\r\n");
      out.write("\r\n");
      out.write("    let currentSemester = null;\r\n");
      out.write("    let currentBranch = null;\r\n");
      out.write("\r\n");
      out.write("    function selectSemester(sem) {\r\n");
      out.write("        currentSemester = sem;\r\n");
      out.write("        currentBranch = null;\r\n");
      out.write("\r\n");
      out.write("        document.querySelectorAll(\".sem-tab\").forEach(function (btn) {\r\n");
      out.write("            btn.classList.toggle(\"active\", btn.textContent.trim() === \"Sem \" + sem);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        document.getElementById(\"selectedSemLabel\").textContent = \"Sem \" + sem;\r\n");
      out.write("        document.getElementById(\"branchCard\").classList.remove(\"d-none\");\r\n");
      out.write("\r\n");
      out.write("        renderBranchGrid();\r\n");
      out.write("        renderTable();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function renderBranchGrid() {\r\n");
      out.write("        const grid = document.getElementById(\"branchGrid\");\r\n");
      out.write("        grid.innerHTML = \"\";\r\n");
      out.write("\r\n");
      out.write("        branches.forEach(function (b) {\r\n");
      out.write("            const count = allStudents.filter(function (s) {\r\n");
      out.write("                return s.semester === currentSemester && s.department === b.code;\r\n");
      out.write("            }).length;\r\n");
      out.write("\r\n");
      out.write("            const col = document.createElement(\"div\");\r\n");
      out.write("            col.className = \"col-md-3 col-sm-6\";\r\n");
      out.write("\r\n");
      out.write("            col.innerHTML =\r\n");
      out.write("                '<div class=\"branch-card' + (currentBranch === b.code ? ' active' : '') + '\" onclick=\"selectBranch(\\'' + b.code + '\\')\">' +\r\n");
      out.write("                    '<div class=\"branch-code\">' + b.code + '</div>' +\r\n");
      out.write("                    '<div class=\"small\">' + b.name + '</div>' +\r\n");
      out.write("                    '<div class=\"branch-count\">' + count + ' student' + (count === 1 ? '' : 's') + '</div>' +\r\n");
      out.write("                '</div>';\r\n");
      out.write("\r\n");
      out.write("            grid.appendChild(col);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function selectBranch(code) {\r\n");
      out.write("        currentBranch = code;\r\n");
      out.write("        renderBranchGrid();\r\n");
      out.write("        renderTable();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function resetFilters() {\r\n");
      out.write("        currentSemester = null;\r\n");
      out.write("        currentBranch = null;\r\n");
      out.write("        document.querySelectorAll(\".sem-tab\").forEach(function (btn) {\r\n");
      out.write("            btn.classList.remove(\"active\");\r\n");
      out.write("        });\r\n");
      out.write("        document.getElementById(\"branchCard\").classList.add(\"d-none\");\r\n");
      out.write("        renderTable();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function renderTable() {\r\n");
      out.write("        let filtered = allStudents;\r\n");
      out.write("\r\n");
      out.write("        if (currentSemester !== null) {\r\n");
      out.write("            filtered = filtered.filter(function (s) { return s.semester === currentSemester; });\r\n");
      out.write("        }\r\n");
      out.write("        if (currentBranch !== null) {\r\n");
      out.write("            filtered = filtered.filter(function (s) { return s.department === currentBranch; });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        const tbody = document.getElementById(\"studentTableBody\");\r\n");
      out.write("        const noResults = document.getElementById(\"noResults\");\r\n");
      out.write("        const filterLabel = document.getElementById(\"tableFilterLabel\");\r\n");
      out.write("\r\n");
      out.write("        let labelText = \"Showing all students\";\r\n");
      out.write("        document.getElementById(\"statBranchLabel\").textContent = \"All Branches\";\r\n");
      out.write("        document.getElementById(\"statSemLabel\").textContent = \"All\";\r\n");
      out.write("\r\n");
      out.write("        if (currentSemester !== null && currentBranch !== null) {\r\n");
      out.write("            labelText = \"Sem \" + currentSemester + \" &middot; \" + currentBranch;\r\n");
      out.write("            document.getElementById(\"statBranchLabel\").textContent = currentBranch;\r\n");
      out.write("            document.getElementById(\"statSemLabel\").textContent = currentSemester;\r\n");
      out.write("        } else if (currentSemester !== null) {\r\n");
      out.write("            labelText = \"Sem \" + currentSemester + \" &middot; all branches\";\r\n");
      out.write("            document.getElementById(\"statSemLabel\").textContent = currentSemester;\r\n");
      out.write("        }\r\n");
      out.write("        filterLabel.innerHTML = labelText;\r\n");
      out.write("        document.getElementById(\"statCountLabel\").textContent = filtered.length;\r\n");
      out.write("\r\n");
      out.write("        tbody.innerHTML = \"\";\r\n");
      out.write("\r\n");
      out.write("        if (filtered.length === 0) {\r\n");
      out.write("            noResults.classList.remove(\"d-none\");\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        noResults.classList.add(\"d-none\");\r\n");
      out.write("\r\n");
      out.write("        filtered.forEach(function (s) {\r\n");
      out.write("            const tr = document.createElement(\"tr\");\r\n");
      out.write("            tr.innerHTML =\r\n");
      out.write("                \"<td>\" + s.id + \"</td>\" +\r\n");
      out.write("                \"<td><strong>\" + s.name + \"</strong></td>\" +\r\n");
      out.write("                \"<td>\" + s.usn + \"</td>\" +\r\n");
      out.write("                \"<td>\" + s.branch + \"</td>\" +\r\n");
      out.write("                '<td><span class=\"badge bg-info\">Sem ' + s.semester + '</span></td>' +\r\n");
      out.write("                \"<td>\" + s.department + \"</td>\" +\r\n");
      out.write("                \"<td>\" +\r\n");
      out.write("                    '<a href=\"' + CONTEXT_PATH + '/edit-student?id=' + s.id + '\" class=\"btn btn-warning btn-sm\">' +\r\n");
      out.write("                        '<i class=\"fa-solid fa-pen\"></i>' +\r\n");
      out.write("                    '</a> ' +\r\n");
      out.write("                    '<a href=\"' + CONTEXT_PATH + '/delete-student?id=' + s.id + '\" class=\"btn btn-danger btn-sm\" ' +\r\n");
      out.write("                        'onclick=\"return confirm(\\'Are you sure you want to delete this student?\\');\">' +\r\n");
      out.write("                        '<i class=\"fa-solid fa-trash\"></i>' +\r\n");
      out.write("                    '</a>' +\r\n");
      out.write("                \"</td>\";\r\n");
      out.write("            tbody.appendChild(tr);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Initial render: show everything until a semester is picked\r\n");
      out.write("    renderTable();\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
